spring.application.name=userdept

server.port = 8080

# dados de conexação com o BD H2
spring.datasource.url = jdbc:h2:mem:testdb
spring.datasource.username = sa
spring.datasource.password = 

# Configuração do client web do banco h2
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console

# Configuração para mostrar o SQL console
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true